---
# tasks file for netzwirt.simple-pki
# create pki structure

- name: create world readable simple-pki directories
  file: 
    path: "{{ item }}"
    state: directory 
    mode: 0755 
    owner: root
  with_items:
    - "{{ simplepki_base_dir }}"
    - "{{ simplepki_ca_base_dir }}"
    - "{{ simplepki_conf_dir }}"
    - "{{ simplepki_certs_dir }}"
    - "{{ simplepki_crls_dir }}"


- name: create protected simple-pki directories
  file: 
    path: "{{ item }}" 
    state: directory 
    mode: 0700 
    owner: root
  with_items:
    - "{{ simplepki_root_ca_dir }}"
    - "{{ simplepki_root_ca_private_dir }}"
    - "{{ simplepki_root_ca_db_dir }}"
    - "{{ simplepki_signing_ca_dir }}"
    - "{{ simplepki_signing_ca_private_dir }}"
    - "{{ simplepki_signing_ca_db_dir }}"


- name: init simple-pki db's
  shell: touch "{{ item }}"
    creates="{{ item }}"
    executable=/bin/bash
  with_items:
    - "{{ simplepki_root_ca_db_dir }}/{{ simplepki_root_ca_name }}.db"
    - "{{ simplepki_root_ca_db_dir }}/{{ simplepki_root_ca_name }}.db.attr"
    - "{{ simplepki_signing_ca_db_dir }}/{{ simplepki_signing_ca_name }}.db"
    - "{{ simplepki_signing_ca_db_dir }}/{{ simplepki_signing_ca_name }}.db.attr"


- name: init simple-pki serials
  shell: echo 01 > "{{ item }}"
    creates="{{ item }}"
    executable=/bin/bash
  with_items:
    - "{{ simplepki_root_ca_db_dir }}/{{ simplepki_root_ca_name }}.crt.srl"
    - "{{ simplepki_root_ca_db_dir }}/{{ simplepki_root_ca_name }}.crl.srl"
    - "{{ simplepki_signing_ca_db_dir }}/{{ simplepki_signing_ca_name }}.crt.srl"
    - "{{ simplepki_signing_ca_db_dir }}/{{ simplepki_signing_ca_name }}.crl.srl"
